# Generated by Django 3.0.8 on 2023-02-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnsafeURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('origianl_url', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
