# Generated by Django 3.0.8 on 2023-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlunmasker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafeurl',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unsafeurl',
            name='origianl_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
